//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Banner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Banner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.Files.Banner", typeof(Banner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BG_Music {
            get {
                return ResourceManager.GetStream("BG_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   __   __   ______  _     _  _     _
        /// (__)_(__) (______)(_)   (_)(_)   (_)
        ///(_) (_) (_)(_)__   (__)_ (_)(_)   (_)
        ///(_) (_) (_)(____)  (_)(_)(_)(_)   (_)
        ///(_)     (_)(_)____ (_)  (__)(_)___(_)
        ///(_)     (_)(______)(_)   (_) (_____)
        ///.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.d8888.  .d8b.  db    db d888888b d8b   db  d888b
        ///88&apos;  YP d8&apos; `8b 88    88   `88&apos;   888o  88 88&apos; Y8b
        ///`8bo.   88ooo88 Y8    8P    88    88V8o 88 88
        ///  `Y8b. 88~~~88 `8b  d8&apos;    88    88 V8o88 88  ooo
        ///db   8D 88   88  `8bd8&apos;    .88.   88  V888 88. ~8~
        ///`8888Y&apos; YP   YP    YP    Y888888P VP   V8P  Y888P
        ///.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    _   _   _   _   _
        ///  / \ / \ / \ / \ / \
        /// ( S | t | a | t | s )
        ///  \_/ \_/ \_/ \_/ \_/
        ///.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 888888888888    db         ,ad8888ba,
        ///     88        d88b       d8&quot;&apos;    `&quot;8b
        ///     88       d8&apos;`8b     d8&apos;
        ///     88      d8&apos;  `8b    88
        ///     88     d8YaaaaY8b   88
        ///     88    d8&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;8b  Y8,
        ///     88   d8&apos;        `8b  Y8a.    .a8P
        ///     88  d8&apos;          `8b  `&quot;Y8888Y&quot;&apos;.
        /// </summary>
        internal static string Tac {
            get {
                return ResourceManager.GetString("Tac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 888888888888  88    ,ad8888ba,
        ///     88       88   d8&quot;&apos;    `&quot;8b
        ///     88       88  d8&apos;
        ///     88       88  88
        ///     88       88  88
        ///     88       88  Y8,
        ///     88       88   Y8a.    .a8P
        ///     88       88    `&quot;Y8888Y&quot;&apos;.
        /// </summary>
        internal static string Tic {
            get {
                return ResourceManager.GetString("Tic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 888888888888  ,ad8888ba,    88888888888
        ///     88      d8&quot;&apos;    `&quot;8b   88
        ///     88     d8&apos;        `8b  88
        ///     88     88          88  88aaaaa
        ///     88     88          88  88&quot;&quot;&quot;&quot;&quot;
        ///     88     Y8,        ,8P  88
        ///     88      Y8a.    .a8P   88
        ///     88       `&quot;Y8888Y&quot;&apos;    88888888888.
        /// </summary>
        internal static string Toe {
            get {
                return ResourceManager.GetString("Toe", resourceCulture);
            }
        }
    }
}
